/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tenaciouspanda.jobstretch.frontend;

import com.tenaciouspanda.jobstretch.Session;
import java.awt.Font;
import java.awt.FontFormatException;
import java.io.IOException;
import java.io.InputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author Simon
 */
public class AddConnectionDeciderPanel extends CardSubpanel {

    /**
     * Creates new form AddConnectionDeciderPanel
     */
    public AddConnectionDeciderPanel(Session session, ViewManager theView) {
        super(session, theView);
        initComponents();
        backBtn.setIcon(new ImageIcon(this.getClass().getResource("/backButton.png")));
        addConnBtn.setIcon(new ImageIcon(this.getClass().getResource("/existingButton.png")));
        addNewConnBtn.setIcon(new ImageIcon(this.getClass().getResource("/newConnectionButton.png")));
        InputStream is = this.getClass().getResourceAsStream("/Oswald-Regular.ttf");
        try {
            Font font = Font.createFont(Font.TRUETYPE_FONT, is);
            Font sizedFont = font.deriveFont(24f);
            Font sizedFont2 = font.deriveFont(32f);
            registrationLabel.setFont(sizedFont2);
            
        } catch (FontFormatException ex) {
            Logger.getLogger(LoginPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(LoginPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backBtn = new javax.swing.JButton();
        registrationLabel = new javax.swing.JLabel();
        addConnBtn = new javax.swing.JButton();
        addNewConnBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setLayout(null);

        backBtn.setBorderPainted(false);
        backBtn.setContentAreaFilled(false);
        backBtn.setFocusPainted(false);
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn);
        backBtn.setBounds(0, 10, 170, 40);

        registrationLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        registrationLabel.setForeground(new java.awt.Color(255, 153, 51));
        registrationLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registrationLabel.setText("Add Connection");
        add(registrationLabel);
        registrationLabel.setBounds(320, 70, 240, 50);

        addConnBtn.setBorderPainted(false);
        addConnBtn.setContentAreaFilled(false);
        addConnBtn.setFocusPainted(false);
        addConnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addConnBtnActionPerformed(evt);
            }
        });
        add(addConnBtn);
        addConnBtn.setBounds(320, 180, 238, 89);

        addNewConnBtn.setBorderPainted(false);
        addNewConnBtn.setContentAreaFilled(false);
        addNewConnBtn.setFocusPainted(false);
        addNewConnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewConnBtnActionPerformed(evt);
            }
        });
        add(addNewConnBtn);
        addNewConnBtn.setBounds(320, 280, 238, 89);

        jLabel6.setIcon(new ImageIcon(this.getClass().getResource("/bg.png")));
        jLabel6.setAlignmentY(0.0F);
        add(jLabel6);
        jLabel6.setBounds(0, 0, 870, 544);
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        view.displayView("DashboardPanel");
    }//GEN-LAST:event_backBtnActionPerformed

    private void addConnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addConnBtnActionPerformed
        view.displayView("AddConnectionPanel");
    }//GEN-LAST:event_addConnBtnActionPerformed

    private void addNewConnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewConnBtnActionPerformed
        view.displayView("AddNewConnectionPanel");
    }//GEN-LAST:event_addNewConnBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addConnBtn;
    private javax.swing.JButton addNewConnBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel registrationLabel;
    // End of variables declaration//GEN-END:variables
}
