package com.tenaciouspanda.jobstretch.frontend;

import com.tenaciouspanda.jobstretch.Session;
import java.awt.Font;
import java.awt.FontFormatException;
import java.io.IOException;
import java.io.InputStream;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Simon
 */
public class AddNewConnectionPanel extends CardSubpanel {

    /**
     * Creates new form AddNewConnectionPanel
     */
    public AddNewConnectionPanel(Session session, ViewManager theView) {
        super(session, theView);
        initComponents();
        backBtn.setIcon(new ImageIcon(this.getClass().getResource("/backButton.png")));
        addBtn.setIcon(new ImageIcon(this.getClass().getResource("/addConnectionButton.png")));
        
                InputStream is = this.getClass().getResourceAsStream("/Oswald-Regular.ttf");
        try {
            Font font = Font.createFont(Font.TRUETYPE_FONT, is);
            Font sizedFont = font.deriveFont(14f);
            Font sizedFont2 = font.deriveFont(32f);
            registrationLabel.setFont(sizedFont2);
            cityLabel.setFont(sizedFont);
            companyNameLabel.setFont(sizedFont);
            employmentStatusLabel.setFont(sizedFont);
            endingLabel.setFont(sizedFont);
            firstNameLabel.setFont(sizedFont);
            jLabel1.setFont(sizedFont);
            jLabel6.setFont(sizedFont);
            lastNameLabel.setFont(sizedFont);
            occupationLabel.setFont(sizedFont);
            startLabel1.setFont(sizedFont);
            stateLabel.setFont(sizedFont);
            summaryLabel.setFont(sizedFont);
            zipCodeLabel.setFont(sizedFont);
            
            
        } catch (FontFormatException ex) {
            Logger.getLogger(LoginPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(LoginPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        employmentStatusComboBox = new javax.swing.JComboBox<String>();
        employmentStatusLabel = new javax.swing.JLabel();
        occupationLabel = new javax.swing.JLabel();
        companyNameLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cityLabel = new javax.swing.JLabel();
        stateLabel = new javax.swing.JLabel();
        zipCodeLabel = new javax.swing.JLabel();
        firstNameField = new javax.swing.JTextField();
        lastNameField = new javax.swing.JTextField();
        occupationField = new javax.swing.JTextField();
        companyNameField = new javax.swing.JTextField();
        streetAddressField = new javax.swing.JTextField();
        cityField = new javax.swing.JTextField();
        stateComboBox = new javax.swing.JComboBox<String>();
        zipCodeField = new javax.swing.JTextField();
        firstNameLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        summaryTextArea = new javax.swing.JTextArea();
        endingLabel = new javax.swing.JLabel();
        startMonthComboBox = new javax.swing.JComboBox<String>();
        startDayComboBox = new javax.swing.JComboBox<String>();
        startYearComboBox = new javax.swing.JComboBox<String>();
        endMonthComboBox = new javax.swing.JComboBox<String>();
        endDayComboBox = new javax.swing.JComboBox<String>();
        endYearComboBox = new javax.swing.JComboBox<String>();
        backBtn = new javax.swing.JButton();
        summaryLabel = new javax.swing.JLabel();
        registrationLabel = new javax.swing.JLabel();
        addBtn = new javax.swing.JButton();
        startLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setLayout(null);

        employmentStatusComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Employed", "Unemployed" }));
        employmentStatusComboBox.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(employmentStatusComboBox);
        employmentStatusComboBox.setBounds(240, 170, 140, 30);

        employmentStatusLabel.setFont(new java.awt.Font("Oswald", 0, 14)); // NOI18N
        employmentStatusLabel.setForeground(new java.awt.Color(255, 255, 255));
        employmentStatusLabel.setText("Employment Status");
        add(employmentStatusLabel);
        employmentStatusLabel.setBounds(90, 170, 140, 30);

        occupationLabel.setFont(new java.awt.Font("Oswald", 0, 14)); // NOI18N
        occupationLabel.setForeground(new java.awt.Color(255, 255, 255));
        occupationLabel.setText("Occupation");
        add(occupationLabel);
        occupationLabel.setBounds(90, 210, 110, 30);

        companyNameLabel.setFont(new java.awt.Font("Oswald", 0, 14)); // NOI18N
        companyNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        companyNameLabel.setText("Company Name");
        add(companyNameLabel);
        companyNameLabel.setBounds(90, 250, 130, 30);

        jLabel1.setFont(new java.awt.Font("Oswald", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Street Address");
        add(jLabel1);
        jLabel1.setBounds(90, 290, 140, 30);

        cityLabel.setFont(new java.awt.Font("Oswald", 0, 14)); // NOI18N
        cityLabel.setForeground(new java.awt.Color(255, 255, 255));
        cityLabel.setText("City");
        add(cityLabel);
        cityLabel.setBounds(90, 330, 70, 30);

        stateLabel.setFont(new java.awt.Font("Oswald", 0, 14)); // NOI18N
        stateLabel.setForeground(new java.awt.Color(255, 255, 255));
        stateLabel.setText("State");
        add(stateLabel);
        stateLabel.setBounds(90, 370, 70, 30);

        zipCodeLabel.setFont(new java.awt.Font("Oswald", 0, 14)); // NOI18N
        zipCodeLabel.setForeground(new java.awt.Color(255, 255, 255));
        zipCodeLabel.setText("Zip Code");
        add(zipCodeLabel);
        zipCodeLabel.setBounds(90, 410, 100, 30);

        firstNameField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(firstNameField);
        firstNameField.setBounds(240, 90, 138, 30);

        lastNameField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(lastNameField);
        lastNameField.setBounds(240, 130, 138, 30);

        occupationField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(occupationField);
        occupationField.setBounds(240, 210, 138, 30);

        companyNameField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        companyNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                companyNameFieldActionPerformed(evt);
            }
        });
        add(companyNameField);
        companyNameField.setBounds(240, 250, 138, 30);

        streetAddressField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(streetAddressField);
        streetAddressField.setBounds(240, 290, 137, 30);

        cityField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(cityField);
        cityField.setBounds(240, 330, 137, 30);

        stateComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "KY", "AR", "HA" }));
        add(stateComboBox);
        stateComboBox.setBounds(240, 370, 70, 30);

        zipCodeField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(zipCodeField);
        zipCodeField.setBounds(240, 410, 137, 30);

        firstNameLabel.setFont(new java.awt.Font("Oswald", 0, 14)); // NOI18N
        firstNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        firstNameLabel.setText("First Name");
        add(firstNameLabel);
        firstNameLabel.setBounds(90, 90, 90, 30);

        lastNameLabel.setFont(new java.awt.Font("Oswald", 0, 14)); // NOI18N
        lastNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        lastNameLabel.setText("Last Name");
        add(lastNameLabel);
        lastNameLabel.setBounds(90, 130, 90, 30);

        summaryTextArea.setColumns(20);
        summaryTextArea.setRows(5);
        summaryTextArea.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setViewportView(summaryTextArea);

        add(jScrollPane1);
        jScrollPane1.setBounds(470, 120, 307, 113);

        endingLabel.setFont(new java.awt.Font("Oswald", 0, 14)); // NOI18N
        endingLabel.setForeground(new java.awt.Color(255, 255, 255));
        endingLabel.setText("End Date");
        add(endingLabel);
        endingLabel.setBounds(470, 340, 110, 30);

        startMonthComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        startMonthComboBox.setToolTipText("");
        startMonthComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startMonthComboBoxActionPerformed(evt);
            }
        });
        add(startMonthComboBox);
        startMonthComboBox.setBounds(520, 380, 50, 30);

        startDayComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        add(startDayComboBox);
        startDayComboBox.setBounds(520, 300, 50, 30);

        startYearComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2016" }));
        add(startYearComboBox);
        startYearComboBox.setBounds(570, 380, 80, 30);

        endMonthComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        endMonthComboBox.setToolTipText("");
        endMonthComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endMonthComboBoxActionPerformed(evt);
            }
        });
        add(endMonthComboBox);
        endMonthComboBox.setBounds(470, 300, 50, 30);

        endDayComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        add(endDayComboBox);
        endDayComboBox.setBounds(470, 380, 50, 30);

        endYearComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2016" }));
        add(endYearComboBox);
        endYearComboBox.setBounds(570, 300, 80, 30);

        backBtn.setBorderPainted(false);
        backBtn.setContentAreaFilled(false);
        backBtn.setFocusPainted(false);
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn);
        backBtn.setBounds(10, 10, 130, 30);

        summaryLabel.setFont(new java.awt.Font("Oswald", 0, 14)); // NOI18N
        summaryLabel.setForeground(new java.awt.Color(255, 255, 255));
        summaryLabel.setText("Summary");
        add(summaryLabel);
        summaryLabel.setBounds(470, 90, 220, 30);

        registrationLabel.setFont(new java.awt.Font("Oswald", 0, 32)); // NOI18N
        registrationLabel.setForeground(new java.awt.Color(255, 153, 51));
        registrationLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registrationLabel.setText("Add New Connection");
        add(registrationLabel);
        registrationLabel.setBounds(260, 10, 350, 40);

        addBtn.setBorderPainted(false);
        addBtn.setContentAreaFilled(false);
        addBtn.setFocusPainted(false);
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        add(addBtn);
        addBtn.setBounds(600, 450, 220, 50);

        startLabel1.setFont(new java.awt.Font("Oswald", 0, 14)); // NOI18N
        startLabel1.setForeground(new java.awt.Color(255, 255, 255));
        startLabel1.setText("Start Date");
        add(startLabel1);
        startLabel1.setBounds(470, 260, 110, 30);

        jLabel6.setIcon(new ImageIcon(this.getClass().getResource("/bg.png")));
        jLabel6.setAlignmentY(0.0F);
        add(jLabel6);
        jLabel6.setBounds(0, 0, 870, 544);
    }// </editor-fold>//GEN-END:initComponents

    private void startMonthComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startMonthComboBoxActionPerformed
        switch(startMonthComboBox.getSelectedIndex()+1) {
            case 1: case 3: case 5:
            case 7: case 8: case 10:
            case 12:
            startDayComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
            break;
            case 4: case 6:
            case 9: case 11:
            startDayComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
            break;
            case 2:
            if ((Integer.parseInt(startYearComboBox.getSelectedItem().toString()) % 4 == 0)) {
                startDayComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29"}));
                break;
            }
            startDayComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28"}));
            break;
            default:
            startDayComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        }
    }//GEN-LAST:event_startMonthComboBoxActionPerformed

    private void endMonthComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endMonthComboBoxActionPerformed
        switch(startMonthComboBox.getSelectedIndex()+1) {
            case 1: case 3: case 5:
            case 7: case 8: case 10:
            case 12:
            endDayComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
            break;
            case 4: case 6:
            case 9: case 11:
            endDayComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
            break;
            case 2:
            if ((Integer.parseInt(endYearComboBox.getSelectedItem().toString()) % 4 == 0)) {
                endDayComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29"}));
                break;
            }
            endDayComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28"}));
            break;
            default:
            endDayComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        }
    }//GEN-LAST:event_endMonthComboBoxActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        view.displayView("DashboardPanel");
    }//GEN-LAST:event_backBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        
        try {
            DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
            Date startDate = df.parse(
                startYearComboBox.getSelectedItem() + "-" +
                startMonthComboBox.getSelectedItem() + "-" +
                startDayComboBox.getSelectedItem()
            );
            Date endDate = df.parse(
                endYearComboBox.getSelectedItem() + "-" +
                endMonthComboBox.getSelectedItem() + "-" +
                endDayComboBox.getSelectedItem()
            );
            int zip = Integer.parseInt(zipCodeField.getText());

            boolean success = session.addNewConnection(
                firstNameField.getText(),
                lastNameField.getText(),
                cityField.getText(),
                streetAddressField.getText(),
                (String)stateComboBox.getSelectedItem(),
                zip,
                occupationField.getText(),
                companyNameField.getText(),
                startDate,
                endDate,
                ((String)employmentStatusComboBox.getSelectedItem()).equals("Employed")
            );
            if(success)
                view.displayView("DashboardPanel");
            else
                view.setStatus("Error adding new connection");
        } catch (ParseException|NumberFormatException ex) {
            view.setStatus("Unable to parse input: " + ex.getMessage());
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void companyNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_companyNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_companyNameFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField cityField;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JTextField companyNameField;
    private javax.swing.JLabel companyNameLabel;
    private javax.swing.JComboBox<String> employmentStatusComboBox;
    private javax.swing.JLabel employmentStatusLabel;
    private javax.swing.JComboBox<String> endDayComboBox;
    private javax.swing.JComboBox<String> endMonthComboBox;
    private javax.swing.JComboBox<String> endYearComboBox;
    private javax.swing.JLabel endingLabel;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField occupationField;
    private javax.swing.JLabel occupationLabel;
    private javax.swing.JLabel registrationLabel;
    private javax.swing.JComboBox<String> startDayComboBox;
    private javax.swing.JLabel startLabel1;
    private javax.swing.JComboBox<String> startMonthComboBox;
    private javax.swing.JComboBox<String> startYearComboBox;
    private javax.swing.JComboBox<String> stateComboBox;
    private javax.swing.JLabel stateLabel;
    private javax.swing.JTextField streetAddressField;
    private javax.swing.JLabel summaryLabel;
    private javax.swing.JTextArea summaryTextArea;
    private javax.swing.JTextField zipCodeField;
    private javax.swing.JLabel zipCodeLabel;
    // End of variables declaration//GEN-END:variables
}
