/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.tenaciouspanda.jobstretch.frontend;

import com.tenaciouspanda.jobstretch.Session;
import com.tenaciouspanda.jobstretch.database.BusLocations;
import com.tenaciouspanda.jobstretch.database.Business;
import com.tenaciouspanda.jobstretch.database.User;

/**
 *
 * @author ekustudent
 */
public class DashboardPanel extends CardSubpanel {
    
    /**
     * Creates new form DashboardPanel
     * @param session
     * @param theView
     */
    public DashboardPanel(Session session, ViewManager theView) {
        super(session, theView);
        initComponents();
    }
    
    @Override
    public void onShow(){
        refresh();
    }
    
    public void refresh(){
        if(companyMapRDB.isSelected()){
            Business[] businesses = session.searchBusinesses(searchTextField.getText());
            showCompanies(businesses);
        }else{
            User[] users = session.searchConnectedUser(searchTextField.getText());
            showConnections(users);
        }
    }
    
    public void showConnections(User[] users){
        connectionList.setListData(users);
        
        mapsPanel.clear();
        for(User u: users){
            if(u.getEmployed() == true)
                mapsPanel.addMarker(u.getLat(), u.getLon(), u.toString());
        }
        view.setStatus("Found " + users.length + " connections");
    }

    public void showCompanies(Business[] businesses){
        connectionList.setListData(businesses);
        
        mapsPanel.clear();
        for(Business b: businesses){
            for(BusLocations bl : b.getLocations())
            mapsPanel.addMarker(bl.getLat(), bl.getLon(), b.toString());
        }
        view.setStatus("Found " + businesses.length + " businesses");
    }
    
    public void viewSelectedDetails(){
        Object o = connectionList.getSelectedValue();
        session.select(o);
        if(o instanceof User){
            view.displayView("PersonDetailPanel");
        }else if(o instanceof Business){
            view.displayView("CompanyDetailPanel");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mapTypeRDBGroup = new javax.swing.ButtonGroup();
        logoutButton = new javax.swing.JButton();
        searchTextField = new javax.swing.JTextField();
        refreshButton = new javax.swing.JButton();
        mapsPanel = new com.tenaciouspanda.jobstretch.MapsPanel();
        viewConnectionDetailsButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        connectionList = new javax.swing.JList<>();
        addConnectionButton = new javax.swing.JButton();
        editUserProfileButton = new javax.swing.JButton();
        addCompanyButton = new javax.swing.JButton();
        connectionMapRDB = new javax.swing.JRadioButton();
        companyMapRDB = new javax.swing.JRadioButton();

        setPreferredSize(new java.awt.Dimension(820, 490));

        logoutButton.setText("Log Out");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        searchTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        refreshButton.setText("Refresh");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        viewConnectionDetailsButton.setText("View Details of Selected");
        viewConnectionDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewConnectionDetailsButtonActionPerformed(evt);
            }
        });

        connectionList.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        connectionList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                connectionListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(connectionList);

        addConnectionButton.setText("Add Connection");
        addConnectionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addConnectionButtonActionPerformed(evt);
            }
        });

        editUserProfileButton.setText("Edit User Profile");
        editUserProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editUserProfileButtonActionPerformed(evt);
            }
        });

        addCompanyButton.setText("Add Company");
        addCompanyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCompanyButtonActionPerformed(evt);
            }
        });

        mapTypeRDBGroup.add(connectionMapRDB);
        connectionMapRDB.setSelected(true);
        connectionMapRDB.setText("Connection Map");
        connectionMapRDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectionMapRDBActionPerformed(evt);
            }
        });

        mapTypeRDBGroup.add(companyMapRDB);
        companyMapRDB.setText("Company Map");
        companyMapRDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                companyMapRDBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addConnectionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(addCompanyButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(viewConnectionDetailsButton, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
                            .addComponent(mapsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(logoutButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(editUserProfileButton)
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(connectionMapRDB)
                            .addComponent(companyMapRDB))
                        .addGap(18, 18, 18)
                        .addComponent(searchTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(refreshButton)))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(refreshButton)
                        .addComponent(logoutButton)
                        .addComponent(editUserProfileButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(connectionMapRDB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(companyMapRDB)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                    .addComponent(mapsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addConnectionButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addCompanyButton))
                    .addComponent(viewConnectionDetailsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        this.session.logout();
        this.view.displayView("LoginPanel");
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void addConnectionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addConnectionButtonActionPerformed
        this.view.displayView("AddConnectionDeciderPanel");
    }//GEN-LAST:event_addConnectionButtonActionPerformed

    private void editUserProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editUserProfileButtonActionPerformed
        this.view.displayView("UserProfilePanel");
    }//GEN-LAST:event_editUserProfileButtonActionPerformed

    private void addCompanyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCompanyButtonActionPerformed
        this.view.displayView("AddCompanyPanel");
    }//GEN-LAST:event_addCompanyButtonActionPerformed

    private void companyMapRDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_companyMapRDBActionPerformed
        refresh();
    }//GEN-LAST:event_companyMapRDBActionPerformed

    private void connectionMapRDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectionMapRDBActionPerformed
        refresh();
    }//GEN-LAST:event_connectionMapRDBActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        refresh();
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void connectionListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_connectionListMouseClicked
        if (evt.getClickCount() == 2) {
            viewSelectedDetails();
        }
    }//GEN-LAST:event_connectionListMouseClicked

    private void viewConnectionDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewConnectionDetailsButtonActionPerformed
        viewSelectedDetails();
    }//GEN-LAST:event_viewConnectionDetailsButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCompanyButton;
    private javax.swing.JButton addConnectionButton;
    private javax.swing.JRadioButton companyMapRDB;
    private javax.swing.JList<Object> connectionList;
    private javax.swing.JRadioButton connectionMapRDB;
    private javax.swing.JButton editUserProfileButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logoutButton;
    private javax.swing.ButtonGroup mapTypeRDBGroup;
    private com.tenaciouspanda.jobstretch.MapsPanel mapsPanel;
    private javax.swing.JButton refreshButton;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JButton viewConnectionDetailsButton;
    // End of variables declaration//GEN-END:variables
}
