/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.tenaciouspanda.jobstretch.frontend;

import com.tenaciouspanda.jobstretch.Session;
import com.tenaciouspanda.jobstretch.database.BusLocations;
import com.tenaciouspanda.jobstretch.database.Business;
import com.tenaciouspanda.jobstretch.database.User;
import java.awt.Color;
import java.awt.Font;
import java.awt.FontFormatException;
import java.io.IOException;
import java.io.InputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author ekustudent
 */
public class DashboardPanel extends CardSubpanel {
    
    /**
     * Creates new form DashboardPanel
     * @param session
     * @param theView
     */
    public DashboardPanel(Session session, ViewManager theView) {
        super(session, theView);
        initComponents();
        logoutButton.setIcon(new ImageIcon(this.getClass().getResource("/LogoutButton.png")));
        refreshButton.setIcon(new ImageIcon(this.getClass().getResource("/Refresh.png")));
        addConnectionButton.setIcon(new ImageIcon(this.getClass().getResource("/addConnectionButton.png")));
        addCompanyButton.setIcon(new ImageIcon(this.getClass().getResource("/addCompanyButton.png")));
        viewConnectionDetailsButton.setIcon(new ImageIcon(this.getClass().getResource("/viewDetails.png")));
        connectionMapRDB.setBackground(new Color(0,0,0,0));
        companyMapRDB.setBackground(new Color(0,0,0,0));
        
        InputStream is = this.getClass().getResourceAsStream("/Oswald-Regular.ttf");
        try {
            Font font = Font.createFont(Font.TRUETYPE_FONT, is);
            Font sizedFont = font.deriveFont(24f);
            editUserProfileButton.setFont(sizedFont);
            connectionMapRDB.setFont(font.deriveFont(16f));
            companyMapRDB.setFont(font.deriveFont(16f));
        } catch (FontFormatException ex) {
            Logger.getLogger(LoginPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(LoginPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    @Override
    public void onShow(){
        refresh();
    }
    
    public void refresh(){
        if(companyMapRDB.isSelected()){
            Business[] businesses = session.searchBusinesses(searchTextField.getText());
            showCompanies(businesses);
        }else{
            User[] users = session.searchConnectedUser(searchTextField.getText());
            showConnections(users);
        }
    }
    
    public void showConnections(User[] users){
        connectionList.setListData(users);
        
        mapsPanel.clear();
        for(User u: users){
            if(u.getEmployed() == true)
                mapsPanel.addMarker(u.getLat(), u.getLon(), u.toString());
        }
        view.setStatus("Found " + users.length + " connections");
    }

    public void showCompanies(Business[] businesses){
        connectionList.setListData(businesses);
        
        mapsPanel.clear();
        for(Business b: businesses){
            for(BusLocations bl : b.getLocations())
            mapsPanel.addMarker(bl.getLat(), bl.getLon(), b.toString());
        }
        view.setStatus("Found " + businesses.length + " businesses");
    }
    
    public void viewSelectedDetails(){
        Object o = connectionList.getSelectedValue();
        session.select(o);
        if(o instanceof User){
            view.displayView("PersonDetailPanel");
        }else if(o instanceof Business){
            view.displayView("CompanyDetailPanel");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mapTypeRDBGroup = new javax.swing.ButtonGroup();
        logoutButton = new javax.swing.JButton();
        searchTextField = new javax.swing.JTextField();
        refreshButton = new javax.swing.JButton();
        mapsPanel = new com.tenaciouspanda.jobstretch.MapsPanel();
        viewConnectionDetailsButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        connectionList = new javax.swing.JList<Object>();
        addConnectionButton = new javax.swing.JButton();
        editUserProfileButton = new javax.swing.JButton();
        addCompanyButton = new javax.swing.JButton();
        connectionMapRDB = new javax.swing.JRadioButton();
        companyMapRDB = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(820, 490));
        setLayout(null);

        logoutButton.setBorderPainted(false);
        logoutButton.setContentAreaFilled(false);
        logoutButton.setFocusPainted(false);
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        add(logoutButton);
        logoutButton.setBounds(40, 0, 240, 60);

        searchTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(searchTextField);
        searchTextField.setBounds(440, 20, 328, 33);

        refreshButton.setBorderPainted(false);
        refreshButton.setContentAreaFilled(false);
        refreshButton.setFocusPainted(false);
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });
        add(refreshButton);
        refreshButton.setBounds(790, 10, 60, 50);
        add(mapsPanel);
        mapsPanel.setBounds(360, 70, 490, 370);

        viewConnectionDetailsButton.setBorderPainted(false);
        viewConnectionDetailsButton.setContentAreaFilled(false);
        viewConnectionDetailsButton.setFocusPainted(false);
        viewConnectionDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewConnectionDetailsButtonActionPerformed(evt);
            }
        });
        add(viewConnectionDetailsButton);
        viewConnectionDetailsButton.setBounds(10, 410, 300, 48);

        connectionList.setBackground(new java.awt.Color(0, 0, 0));
        connectionList.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        connectionList.setForeground(new java.awt.Color(255, 255, 255));
        connectionList.setSelectionBackground(new java.awt.Color(255, 153, 51));
        connectionList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                connectionListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(connectionList);

        add(jScrollPane1);
        jScrollPane1.setBounds(10, 70, 300, 330);

        addConnectionButton.setBorderPainted(false);
        addConnectionButton.setContentAreaFilled(false);
        addConnectionButton.setFocusPainted(false);
        addConnectionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addConnectionButtonActionPerformed(evt);
            }
        });
        add(addConnectionButton);
        addConnectionButton.setBounds(360, 450, 240, 50);

        editUserProfileButton.setBackground(new java.awt.Color(255, 153, 51));
        editUserProfileButton.setForeground(new java.awt.Color(255, 153, 51));
        editUserProfileButton.setText("Edit User Profile");
        editUserProfileButton.setBorderPainted(false);
        editUserProfileButton.setContentAreaFilled(false);
        editUserProfileButton.setFocusPainted(false);
        editUserProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editUserProfileButtonActionPerformed(evt);
            }
        });
        add(editUserProfileButton);
        editUserProfileButton.setBounds(10, 460, 300, 50);

        addCompanyButton.setBorderPainted(false);
        addCompanyButton.setContentAreaFilled(false);
        addCompanyButton.setFocusPainted(false);
        addCompanyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCompanyButtonActionPerformed(evt);
            }
        });
        add(addCompanyButton);
        addCompanyButton.setBounds(610, 450, 240, 50);

        mapTypeRDBGroup.add(connectionMapRDB);
        connectionMapRDB.setForeground(new java.awt.Color(255, 255, 255));
        connectionMapRDB.setSelected(true);
        connectionMapRDB.setText("Connection Map");
        connectionMapRDB.setContentAreaFilled(false);
        connectionMapRDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectionMapRDBActionPerformed(evt);
            }
        });
        add(connectionMapRDB);
        connectionMapRDB.setBounds(310, 10, 130, 23);

        mapTypeRDBGroup.add(companyMapRDB);
        companyMapRDB.setForeground(new java.awt.Color(255, 255, 255));
        companyMapRDB.setText("Company Map");
        companyMapRDB.setContentAreaFilled(false);
        companyMapRDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                companyMapRDBActionPerformed(evt);
            }
        });
        add(companyMapRDB);
        companyMapRDB.setBounds(310, 40, 120, 23);

        jLabel5.setIcon(new ImageIcon(this.getClass().getResource("/bg.png")));
        jLabel5.setAlignmentY(0.0F);
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(jLabel5);
        jLabel5.setBounds(0, 0, 867, 544);
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        this.session.logout();
        this.view.displayView("LoginPanel");
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void addConnectionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addConnectionButtonActionPerformed
        this.view.displayView("AddConnectionDeciderPanel");
    }//GEN-LAST:event_addConnectionButtonActionPerformed

    private void editUserProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editUserProfileButtonActionPerformed
        this.view.displayView("UserProfilePanel");
    }//GEN-LAST:event_editUserProfileButtonActionPerformed

    private void addCompanyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCompanyButtonActionPerformed
        this.view.displayView("AddCompanyPanel");
    }//GEN-LAST:event_addCompanyButtonActionPerformed

    private void companyMapRDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_companyMapRDBActionPerformed
        refresh();
    }//GEN-LAST:event_companyMapRDBActionPerformed

    private void connectionMapRDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectionMapRDBActionPerformed
        refresh();
    }//GEN-LAST:event_connectionMapRDBActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        refresh();
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void connectionListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_connectionListMouseClicked
        if (evt.getClickCount() == 2) {
            viewSelectedDetails();
        }
    }//GEN-LAST:event_connectionListMouseClicked

    private void viewConnectionDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewConnectionDetailsButtonActionPerformed
        viewSelectedDetails();
    }//GEN-LAST:event_viewConnectionDetailsButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCompanyButton;
    private javax.swing.JButton addConnectionButton;
    private javax.swing.JRadioButton companyMapRDB;
    private javax.swing.JList<Object> connectionList;
    private javax.swing.JRadioButton connectionMapRDB;
    private javax.swing.JButton editUserProfileButton;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logoutButton;
    private javax.swing.ButtonGroup mapTypeRDBGroup;
    private com.tenaciouspanda.jobstretch.MapsPanel mapsPanel;
    private javax.swing.JButton refreshButton;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JButton viewConnectionDetailsButton;
    // End of variables declaration//GEN-END:variables
}
