/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.tenaciouspanda.jobstretch.frontend;

import com.tenaciouspanda.jobstretch.Session;
import java.awt.Font;
import java.awt.FontFormatException;
import java.io.IOException;
import java.io.InputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author Simon
 */
public class UserProfilePanel extends CardSubpanel {
    
    /**
     * Creates new form UserProfilePanel
     * @param session
     */
    public UserProfilePanel(Session session, ViewManager theView) {
        super(session, theView);
        initComponents();
        backButton.setIcon(new ImageIcon(this.getClass().getResource("/backButton.png")));
        AddEmploymentHistoryButton.setIcon(new ImageIcon(this.getClass().getResource("/addEmploymentButton.png")));
        
                InputStream is = this.getClass().getResourceAsStream("/Oswald-Regular.ttf");
        try {
            Font font = Font.createFont(Font.TRUETYPE_FONT, is);
            Font sizedFont = font.deriveFont(24f);
            Font sizedFont2 = font.deriveFont(32f);
            Font sizedFont3 = font.deriveFont(14f);
            Font sizedFont4 = font.deriveFont(12f);
            jLabel3.setFont(sizedFont2);
            avatarPlaceholder.setFont(sizedFont3);
            userSummaryLabel.setFont(sizedFont);
            changeAvatarButton.setFont(sizedFont4);
            editUserSummary.setFont(sizedFont3);
            jLabel1.setFont(sizedFont);
            jLabel2.setFont(sizedFont);
            employmentStatusLabel.setFont(sizedFont3);
            occupationLabel.setFont(sizedFont3);
            companyNameLabel.setFont(sizedFont3);
            jLabel4.setFont(sizedFont3);
            cityLabel.setFont(sizedFont3);
            stateLabel.setFont(sizedFont3);
            zipCodeLabel.setFont(sizedFont3);
            
        } catch (FontFormatException ex) {
            Logger.getLogger(LoginPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(LoginPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userSummaryLabel = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        editUserSummary = new javax.swing.JButton();
        avatarPlaceholder = new javax.swing.JLabel();
        changeAvatarButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<String>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        employmentStatusLabel = new javax.swing.JLabel();
        employmentStatusComboBox = new javax.swing.JComboBox<String>();
        occupationLabel = new javax.swing.JLabel();
        occupationField = new javax.swing.JTextField();
        companyNameLabel = new javax.swing.JLabel();
        companyNameField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        streetAddressField = new javax.swing.JTextField();
        cityLabel = new javax.swing.JLabel();
        cityField = new javax.swing.JTextField();
        stateLabel = new javax.swing.JLabel();
        stateComboBox = new javax.swing.JComboBox<String>();
        zipCodeLabel = new javax.swing.JLabel();
        zipCodeField = new javax.swing.JTextField();
        AddEmploymentHistoryButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setLayout(null);

        userSummaryLabel.setFont(new java.awt.Font("Oswald", 0, 24)); // NOI18N
        userSummaryLabel.setForeground(new java.awt.Color(255, 255, 255));
        userSummaryLabel.setText("Summary");
        add(userSummaryLabel);
        userSummaryLabel.setBounds(250, 120, 110, 40);

        backButton.setBorderPainted(false);
        backButton.setContentAreaFilled(false);
        backButton.setFocusPainted(false);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton);
        backButton.setBounds(720, 480, 130, 30);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setViewportView(jTextArea1);

        add(jScrollPane1);
        jScrollPane1.setBounds(20, 160, 328, 130);

        editUserSummary.setFont(new java.awt.Font("Oswald", 0, 14)); // NOI18N
        editUserSummary.setForeground(new java.awt.Color(255, 153, 51));
        editUserSummary.setText("Edit");
        editUserSummary.setBorder(null);
        editUserSummary.setBorderPainted(false);
        editUserSummary.setContentAreaFilled(false);
        editUserSummary.setFocusPainted(false);
        editUserSummary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editUserSummaryActionPerformed(evt);
            }
        });
        add(editUserSummary);
        editUserSummary.setBounds(300, 290, 60, 20);

        avatarPlaceholder.setBackground(new java.awt.Color(255, 255, 255));
        avatarPlaceholder.setFont(new java.awt.Font("Oswald", 0, 14)); // NOI18N
        avatarPlaceholder.setForeground(new java.awt.Color(255, 255, 255));
        avatarPlaceholder.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        avatarPlaceholder.setText("Avatar Placeholder");
        avatarPlaceholder.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        add(avatarPlaceholder);
        avatarPlaceholder.setBounds(20, 10, 116, 107);

        changeAvatarButton.setFont(new java.awt.Font("Oswald", 0, 12)); // NOI18N
        changeAvatarButton.setForeground(new java.awt.Color(255, 153, 51));
        changeAvatarButton.setText("Upload / Change Avatar");
        changeAvatarButton.setBorder(null);
        changeAvatarButton.setBorderPainted(false);
        changeAvatarButton.setContentAreaFilled(false);
        changeAvatarButton.setFocusPainted(false);
        changeAvatarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeAvatarButtonActionPerformed(evt);
            }
        });
        add(changeAvatarButton);
        changeAvatarButton.setBounds(10, 120, 130, 40);

        jList1.setBackground(new java.awt.Color(0, 0, 0));
        jList1.setForeground(new java.awt.Color(255, 255, 255));
        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.setSelectionBackground(new java.awt.Color(255, 153, 51));
        jScrollPane2.setViewportView(jList1);

        add(jScrollPane2);
        jScrollPane2.setBounds(20, 370, 330, 140);

        jLabel1.setFont(new java.awt.Font("Oswald", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Past Employers");
        add(jLabel1);
        jLabel1.setBounds(180, 330, 200, 30);

        jLabel2.setFont(new java.awt.Font("Oswald", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Employment Data");
        add(jLabel2);
        jLabel2.setBounds(520, 20, 190, 30);

        jLabel3.setFont(new java.awt.Font("Oswald", 0, 32)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("User Profile");
        add(jLabel3);
        jLabel3.setBounds(190, 10, 160, 30);

        employmentStatusLabel.setFont(new java.awt.Font("Oswald", 0, 14)); // NOI18N
        employmentStatusLabel.setForeground(new java.awt.Color(255, 255, 255));
        employmentStatusLabel.setText("Employment Status");
        add(employmentStatusLabel);
        employmentStatusLabel.setBounds(440, 80, 130, 20);

        employmentStatusComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Employed", "Unemployed" }));
        employmentStatusComboBox.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(employmentStatusComboBox);
        employmentStatusComboBox.setBounds(600, 70, 130, 30);

        occupationLabel.setFont(new java.awt.Font("Oswald", 0, 14)); // NOI18N
        occupationLabel.setForeground(new java.awt.Color(255, 255, 255));
        occupationLabel.setText("Occupation");
        add(occupationLabel);
        occupationLabel.setBounds(440, 120, 100, 20);

        occupationField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(occupationField);
        occupationField.setBounds(600, 110, 130, 30);

        companyNameLabel.setFont(new java.awt.Font("Oswald", 0, 14)); // NOI18N
        companyNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        companyNameLabel.setText("Company Name");
        add(companyNameLabel);
        companyNameLabel.setBounds(440, 150, 100, 30);

        companyNameField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(companyNameField);
        companyNameField.setBounds(600, 150, 130, 30);

        jLabel4.setFont(new java.awt.Font("Oswald", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Street Address");
        add(jLabel4);
        jLabel4.setBounds(440, 190, 120, 30);

        streetAddressField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(streetAddressField);
        streetAddressField.setBounds(600, 190, 234, 30);

        cityLabel.setFont(new java.awt.Font("Oswald", 0, 14)); // NOI18N
        cityLabel.setForeground(new java.awt.Color(255, 255, 255));
        cityLabel.setText("City");
        add(cityLabel);
        cityLabel.setBounds(440, 230, 40, 30);

        cityField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(cityField);
        cityField.setBounds(600, 230, 137, 30);

        stateLabel.setFont(new java.awt.Font("Oswald", 0, 14)); // NOI18N
        stateLabel.setForeground(new java.awt.Color(255, 255, 255));
        stateLabel.setText("State");
        add(stateLabel);
        stateLabel.setBounds(440, 270, 50, 30);

        stateComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "KY", "AR", "HA" }));
        stateComboBox.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(stateComboBox);
        stateComboBox.setBounds(600, 270, 70, 30);

        zipCodeLabel.setFont(new java.awt.Font("Oswald", 0, 14)); // NOI18N
        zipCodeLabel.setForeground(new java.awt.Color(255, 255, 255));
        zipCodeLabel.setText("Zip Code");
        add(zipCodeLabel);
        zipCodeLabel.setBounds(440, 310, 60, 30);

        zipCodeField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(zipCodeField);
        zipCodeField.setBounds(600, 310, 104, 30);

        AddEmploymentHistoryButton.setBorderPainted(false);
        AddEmploymentHistoryButton.setContentAreaFilled(false);
        AddEmploymentHistoryButton.setFocusPainted(false);
        AddEmploymentHistoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEmploymentHistoryButtonActionPerformed(evt);
            }
        });
        add(AddEmploymentHistoryButton);
        AddEmploymentHistoryButton.setBounds(480, 370, 200, 50);

        jLabel5.setIcon(new ImageIcon(this.getClass().getResource("/bg.png")));
        jLabel5.setAlignmentY(0.0F);
        add(jLabel5);
        jLabel5.setBounds(0, 0, 867, 544);
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.view.displayView("DashboardPanel");
    }//GEN-LAST:event_backButtonActionPerformed

    private void editUserSummaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editUserSummaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editUserSummaryActionPerformed

    private void changeAvatarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeAvatarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_changeAvatarButtonActionPerformed

    private void AddEmploymentHistoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEmploymentHistoryButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddEmploymentHistoryButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddEmploymentHistoryButton;
    private javax.swing.JLabel avatarPlaceholder;
    private javax.swing.JButton backButton;
    private javax.swing.JButton changeAvatarButton;
    private javax.swing.JTextField cityField;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JTextField companyNameField;
    private javax.swing.JLabel companyNameLabel;
    private javax.swing.JButton editUserSummary;
    private javax.swing.JComboBox<String> employmentStatusComboBox;
    private javax.swing.JLabel employmentStatusLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField occupationField;
    private javax.swing.JLabel occupationLabel;
    private javax.swing.JComboBox<String> stateComboBox;
    private javax.swing.JLabel stateLabel;
    private javax.swing.JTextField streetAddressField;
    private javax.swing.JLabel userSummaryLabel;
    private javax.swing.JTextField zipCodeField;
    private javax.swing.JLabel zipCodeLabel;
    // End of variables declaration//GEN-END:variables
}
