/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.tenaciouspanda.jobstretch.frontend;

import com.tenaciouspanda.jobstretch.Session;
import java.awt.Font;
import java.awt.FontFormatException;
import java.io.IOException;
import java.io.InputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author Simon
 */
public class UserFoundPanel extends CardSubpanel {

    /**
     * Creates new form UserFoundPanel
     * @param session
     * @param theView
     */
    public UserFoundPanel(Session session, ViewManager theView) {
        super(session, theView);
        initComponents();
        noButton.setIcon(new ImageIcon(this.getClass().getResource("/noButton.png")));
        yesButton.setIcon(new ImageIcon(this.getClass().getResource("/yesButton.png")));

        Font sizedFont = view.getFont(24);
        Font sizedFont2 = view.getFont(32);
        userFoundLabel.setFont(sizedFont2);
        claimUserLabel.setFont(sizedFont);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userFoundLabel = new javax.swing.JLabel();
        claimUserLabel = new javax.swing.JLabel();
        yesButton = new javax.swing.JButton();
        noButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setLayout(null);

        userFoundLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        userFoundLabel.setForeground(new java.awt.Color(255, 153, 51));
        userFoundLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userFoundLabel.setText("User Found With Matching Information");
        add(userFoundLabel);
        userFoundLabel.setBounds(140, 40, 590, 90);

        claimUserLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        claimUserLabel.setForeground(new java.awt.Color(255, 255, 255));
        claimUserLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        claimUserLabel.setText("Claim this User?");
        add(claimUserLabel);
        claimUserLabel.setBounds(330, 150, 210, 50);

        yesButton.setBorderPainted(false);
        yesButton.setContentAreaFilled(false);
        yesButton.setFocusPainted(false);
        yesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesButtonActionPerformed(evt);
            }
        });
        add(yesButton);
        yesButton.setBounds(280, 220, 140, 50);

        noButton.setBorderPainted(false);
        noButton.setContentAreaFilled(false);
        noButton.setFocusPainted(false);
        noButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noButtonActionPerformed(evt);
            }
        });
        add(noButton);
        noButton.setBounds(440, 220, 140, 50);

        jLabel5.setIcon(new ImageIcon(this.getClass().getResource("/bg.png")));
        jLabel5.setAlignmentY(0.0F);
        add(jLabel5);
        jLabel5.setBounds(0, 0, 867, 544);
    }// </editor-fold>//GEN-END:initComponents

    private void yesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yesButtonActionPerformed

    private void noButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel claimUserLabel;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton noButton;
    private javax.swing.JLabel userFoundLabel;
    private javax.swing.JButton yesButton;
    // End of variables declaration//GEN-END:variables
}
